[package]
name = "mxyzptlk"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12.0"
log = "0.4.17"
rand = "0.8.5"
rand_chacha = "0.3.1"
pancurses = "0.17"
log4rs = "1.2.0"
