# Valid colors:
#  2 = BLACK
#  3 = RED
#  4 = GREEN
#  5 = YELLOW
#  6 = BLUE
#  7 = MAGENTA
#  8 = CYAN
#  9 = WHITE
foreground: 9
background: 2
# Logging - "enabled" or "disabled"
logging: disabled
# Recoverable(ish) error handling, which is useful for debugging
#  continue_warn_always - warn every time and allow user to continue
#  continue_warn_once - warn once per error code and allow user to continue
#  ignore - attempt to continue without any notice (default)
#  abort - abort execution with an error message
error_handling: ignore
# Volume scaling default value is based on limited platform testing as follows:
#  macos: 128.0
#  linux (KDE plasma + pipewire): 8.0
#  windows: 12.0
# If sound playback is too quiet or too loud, uncomment the line below and change
# it to something slightly higher or lower than the platform default, then adjust
# as needed.
# volume_factor: 128.0
